import { Question } from './types';

export const DEFAULT_QUESTIONS: Question[] = [
  {
    id: 'q1',
    question: 'Name something you associate with St. Patrick\'s Day',
    answers: [
      { text: 'Green/Wearing Green', points: 38 },
      { text: 'Shamrocks/Clovers', points: 25 },
      { text: 'Beer/Drinking', points: 15 },
      { text: 'Leprechauns', points: 10 },
      { text: 'Parades', points: 6 },
      { text: 'Pot of Gold', points: 4 },
      { text: 'Ireland', points: 2 },
    ],
    isUsed: false,
  },
  {
    id: 'q2',
    question: 'Name something green',
    answers: [
      { text: 'Grass', points: 42 },
      { text: 'Trees/Leaves', points: 20 },
      { text: 'Money', points: 15 },
      { text: 'Broccoli', points: 8 },
      { text: 'Frogs', points: 6 },
      { text: 'Peas', points: 5 },
      { text: 'The Hulk', points: 3 },
      { text: 'Shamrock Shake', points: 1 },
    ],
    isUsed: false,
  },
  {
    id: 'q3',
    question: 'Name something you\'d find in Ireland',
    answers: [
      { text: 'Pubs/Bars', points: 35 },
      { text: 'Castles', points: 22 },
      { text: 'Green Hills/Countryside', points: 18 },
      { text: 'Sheep', points: 10 },
      { text: 'Cliffs of Moher', points: 8 },
      { text: 'Guinness', points: 5 },
      { text: 'Leprechauns', points: 2 },
    ],
    isUsed: false,
  },
  {
    id: 'q4',
    question: 'Name a famous Irish person',
    answers: [
      { text: 'Conor McGregor', points: 30 },
      { text: 'Bono/U2', points: 22 },
      { text: 'Liam Neeson', points: 18 },
      { text: 'Colin Farrell', points: 12 },
      { text: 'Saoirse Ronan', points: 8 },
      { text: 'Oscar Wilde', points: 6 },
      { text: 'Ed Sheeran', points: 4 },
    ],
    isUsed: false,
  },
  {
    id: 'q5',
    question: 'Name something you drink on St. Patrick\'s Day',
    answers: [
      { text: 'Beer/Green Beer', points: 45 },
      { text: 'Guinness', points: 20 },
      { text: 'Irish Whiskey', points: 12 },
      { text: 'Irish Coffee', points: 10 },
      { text: 'Jameson', points: 7 },
      { text: 'Baileys', points: 4 },
      { text: 'Shamrock Shake', points: 2 },
    ],
    isUsed: false,
  },
  {
    id: 'q6',
    question: 'Name a word or phrase with "luck" in it',
    answers: [
      { text: 'Good Luck', points: 35 },
      { text: 'Luck of the Irish', points: 25 },
      { text: 'Lucky Charm(s)', points: 15 },
      { text: 'Lucky Break', points: 10 },
      { text: 'Pot Luck', points: 8 },
      { text: 'Lucky Star', points: 5 },
      { text: 'Dumb Luck', points: 2 },
    ],
    isUsed: false,
  },
  {
    id: 'q7',
    question: 'Name something a leprechaun might carry',
    answers: [
      { text: 'Pot of Gold', points: 40 },
      { text: 'Shamrock/Clover', points: 20 },
      { text: 'Walking Stick/Shillelagh', points: 15 },
      { text: 'A Pipe', points: 10 },
      { text: 'Shoes/Cobbler Tools', points: 8 },
      { text: 'Rainbow', points: 5 },
      { text: 'A Hat', points: 2 },
    ],
    isUsed: false,
  },
  {
    id: 'q8',
    question: 'Name something that brings good luck',
    answers: [
      { text: 'Four-Leaf Clover', points: 35 },
      { text: 'Horseshoe', points: 22 },
      { text: "Rabbit's Foot", points: 18 },
      { text: 'Penny/Finding Money', points: 10 },
      { text: 'Wishbone', points: 7 },
      { text: 'Shooting Star', points: 5 },
      { text: 'Crossing Fingers', points: 3 },
    ],
    isUsed: false,
  },
  {
    id: 'q9',
    question: 'Name an Irish food or dish',
    answers: [
      { text: 'Corned Beef & Cabbage', points: 38 },
      { text: 'Shepherd\'s Pie', points: 22 },
      { text: 'Irish Stew', points: 16 },
      { text: 'Soda Bread', points: 10 },
      { text: 'Fish & Chips', points: 7 },
      { text: 'Potatoes/Colcannon', points: 5 },
      { text: 'Boxty', points: 2 },
    ],
    isUsed: false,
  },
  {
    id: 'q10',
    question: 'Name something you\'d see at a St. Patrick\'s Day parade',
    answers: [
      { text: 'Floats', points: 30 },
      { text: 'People in Green', points: 22 },
      { text: 'Bagpipes/Music', points: 16 },
      { text: 'Irish Dancers', points: 12 },
      { text: 'Marching Bands', points: 10 },
      { text: 'Shamrocks', points: 6 },
      { text: 'Beer/Drinking', points: 4 },
    ],
    isUsed: false,
  },
  {
    id: 'q11',
    question: 'Name something associated with the color gold',
    answers: [
      { text: 'Gold/Jewelry', points: 35 },
      { text: 'Money/Coins', points: 20 },
      { text: 'Sunshine', points: 15 },
      { text: 'Trophy/Medal', points: 12 },
      { text: 'Crown/Royalty', points: 8 },
      { text: 'Wedding Ring', points: 6 },
      { text: 'Pot of Gold', points: 4 },
    ],
    isUsed: false,
  },
  {
    id: 'q12',
    question: 'Name something people do when they\'re feeling lucky',
    answers: [
      { text: 'Gamble/Play Lottery', points: 42 },
      { text: 'Buy a Scratch Ticket', points: 18 },
      { text: 'Go to Casino', points: 15 },
      { text: 'Make a Bet', points: 10 },
      { text: 'Ask Someone Out', points: 8 },
      { text: 'Try Something New', points: 5 },
      { text: 'Make a Wish', points: 2 },
    ],
    isUsed: false,
  },
  {
    id: 'q13',
    question: 'Name a reason someone might get pinched on St. Patrick\'s Day',
    answers: [
      { text: 'Not Wearing Green', points: 65 },
      { text: 'Forgot It Was St. Paddy\'s', points: 15 },
      { text: 'Wearing Orange', points: 10 },
      { text: 'Being Grumpy', points: 5 },
      { text: 'No Shamrock', points: 5 },
    ],
    isUsed: false,
  },
  {
    id: 'q14',
    question: 'Name a magical or mythical creature from Irish folklore',
    answers: [
      { text: 'Leprechaun', points: 45 },
      { text: 'Fairy/Faerie', points: 20 },
      { text: 'Banshee', points: 15 },
      { text: 'Dragon', points: 8 },
      { text: 'Selkie', points: 6 },
      { text: 'Changeling', points: 4 },
      { text: 'Pooka', points: 2 },
    ],
    isUsed: false,
  },
  {
    id: 'q15',
    question: 'Name something you\'d find at the end of a rainbow',
    answers: [
      { text: 'Pot of Gold', points: 55 },
      { text: 'Leprechaun', points: 18 },
      { text: 'Nothing', points: 10 },
      { text: 'Another Rainbow', points: 7 },
      { text: 'Treasure', points: 6 },
      { text: 'Happiness', points: 4 },
    ],
    isUsed: false,
  },
];
